=== ahochsteger/gmail-processor/src/lib/config/v1/config-schema-v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "globalFilter": {
      "default": "has:attachment -in:trash -in:drafts -in:spam",
      "type": "string",
      "description": "Global filter"
    },
    "processedLabel": {
      "type": "string",
      "description": "GMail label for processed threads (will be created, if not existing)"
    },
    "sleepTime": {
      "type": "number",
      "description": "Sleep time in milliseconds between processed messages"
    },
    "maxRuntime": {
      "type": "number",
      "description": "Maximum script runtime in seconds (google scripts will be killed after 5 minutes)"
    },
    "newerThan": {
      "type": "string",
      "description": "Only process message newer than (leave empty for no restriction; use d, m and y for day, month and year)"
    },
    "timezone": {
      "type": "string",
      "description": "Timezone for date/time operations"
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "archive": {
            "default": false,
            "description": "Archive thread after processing",
            "type": "boolean"
          },
          "filenameFrom": {
            "default": "",
            "description": "Rename matching attachments from the given filename",
            "type": "string"
          },
          "filenameFromRegexp": {
            "default": "",
            "description": "Rename matching attachments from the given filename regex",
            "type": "string"
          },
          "filenameTo": {
            "default": "",
            "description": "Rename matching attachments to the given filename",
            "type": "string"
          },
          "filter": {
            "default": "",
            "description": "Search filter for threads",
            "type": "string"
          },
          "folder": {
            "default": "",
            "description": "GDrive folder to store attachments to",
            "type": "string"
          },
          "newerThan": {
            "default": "",
            "description": "Restrict to threads containing messages newer than the given relative date/time",
            "type": "string"
          },
          "parentFolderId": {
            "default": "",
            "description": "Parent folder ID to be used (for shared drives)",
            "type": "string"
          },
          "ruleLabel": {
            "default": "",
            "description": "Add the given label to the processed thread",
            "type": "string"
          },
          "saveMessagePDF": {
            "default": false,
            "description": "Save the message to PDF",
            "type": "boolean"
          },
          "saveThreadPDF": {
            "default": false,
            "description": "Save the thread to PDF",
            "type": "boolean"
          },
          "skipPDFHeader": {
            "default": false,
            "description": "Skip header for PDF",
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
      "description": "Processing rules"
    }
  },
  "required": [
    "processedLabel",
    "sleepTime",
    "maxRuntime",
    "newerThan",
    "timezone",
    "rules"
  ],
  "additionalProperties": false,
  "title": "GMail2GDrive Config (v1)"
}

=== ahochsteger/gmail-processor/src/examples/migrations/migrationAdvanced.json
{
  "globalFilter": "has:attachment -in:trash -in:drafts -in:spam",
  "processedLabel": "gmail2gdrive/client-test",
  "sleepTime": 100,
  "maxRuntime": 280,
  "newerThan": "1d",
  "timezone": "GMT",
  "rules": [
    {
      "filter": "to:my.name+scans@gmail.com",
      "folder": "'Scans'-yyyy-MM-dd"
    },
    {
      "filter": "from:example1@example.com",
      "folder": "'Examples/example1'"
    },
    {
      "filter": "from:example2@example.com",
      "folder": "'Examples/example2'",
      "filenameFromRegexp": ".*.pdf$"
    },
    {
      "filter": "(from:example3a@example.com OR from:example3b@example.com)",
      "folder": "'Examples/example3ab'",
      "filenameTo": "'file-'yyyy-MM-dd-'%s.txt'",
      "archive": true
    },
    {
      "filter": "label:PDF",
      "saveThreadPDF": true,
      "folder": "'PDF Emails'"
    },
    {
      "filter": "from:example4@example.com",
      "folder": "'Examples/example4'",
      "filenameFrom": "file.txt",
      "filenameTo": "'file-'yyyy-MM-dd-'%s.txt'"
    }
  ]
}
